#Configuración de las fuentes de datos
records_to_process: all
sources:
  - name: "nacimientos"
    separator: "," #"|"
    input_path: "hdfs:///rawdata/vitales/nacimientos/"
    output_path: "hdfs:///stagedata/vitales/nacimientos_test5/"
    input_files: ["ConsultarNacimientos_2008_a_2016.txt", "ConsultarNacimientos_2017_a_2023.txt"]
    #input_files: ["ConsultarNacimientos2008-2023_V3.csv"]
    #input_columns: ['PersonaID', 'FechaNacimientoAAAAMM', 'Sexo', 'RegimenAfiliacionSGSSS', 'Administradora', 'CodigoPertenenciaEtnica', 'municipioResidencia', 'SemanasGestacion', 'EdadMadreMomentoDiagnostico', 'FechaCertificadoAAAAMM', 'IpsDondeRealizaParto', 'Peso', 'AnoID']
    input_columns: ['PersonaID', 'FechaNacimientoAAAAMM', 'Sexo', 'RegimenAfiliacionSGSSS', 'Administradora', 'CodigoPertenenciaEtnica', 'municipioResidencia', 'SemanasGestacion', 'EdadMadreMomentoDiagnostico', 'FechaCertificadoAAAAMM', 'IpsDondeRealizaParto', 'Peso']
    #output_columns: ["personaid", "fechanacimiento", "sexo", "regimenafiliacion", "administradora", "codigoetnia", "municipioresidencia", "semanasgestacion", "edadmadre", "fechacertificado", "ips", "peso", "anoid"]
    output_columns: ["personaid", "fechanacimiento", "sexo", "regimenafiliacion", "administradora", "codigoetnia", "municipioresidencia", "semanasgestacion", "edadmadre", "fechacertificado", "ips", "peso"]
    column_renames:
      - original: "PersonaID"
        new: "personaid"
      - original: "FechaNacimientoAAAAMM"
        new: "fechanacimiento"
      - original: "Sexo"
        new: "sexo"
      - original: "RegimenAfiliacionSGSSS"
        new: "regimenafiliacion"
      - original: "Administradora"
        new: "administradora"
      - original: "CodigoPertenenciaEtnica"
        new: "codigoetnia"
      - original: "municipioResidencia"
        new: "municipioresidencia"
      - original: "SemanasGestacion"
        new: "semanasgestacion"
      - original: "EdadMadreMomentoDiagnostico"
        new: "edadmadre"
      - original: "FechaCertificadoAAAAMM"
        new: "fechacertificado"
      - original: "IpsDondeRealizaParto"
        new: "ips"
      - original: "Peso"
        new: "peso"
     # - original: "AnoID"
     #   new: "anoid"    
    process: true
    error_file: "/home/agora/Data_lake/ETL/errors/vitales/nacimientos/nacimientos_errados_test.txt"
    encoding: "latin1"
  - name: "defunciones"
    input_path: "hdfs:///rawdata/vitales/defunciones/"
    output_path: "hdfs:///stagedata/vitales/defunciones_test/"
    input_files: ["ConsultarDefunciones_2008_a_2016.txt", "ConsultarDefunciones_2017_a_2023.txt"]
    input_columns: ['PersonaID', 'Sexo', 'RegimenAfiliacionSGSSS', 'Administradora', 'CodigoPertenenciaEtnica', 'municipioResidencia', 'SemanasGestacion', 'EdadMadreMomentoDiagnostico', 'FechaDefuncionAAAAMM', 'IpsDondeRealizaParto', 'Peso', 'AnoID']
    output_columns: ["personaid", "sexo", "regimenafiliacion", "administradora", "codigoetnia", "municipioresidencia", "semanasgestacion", "edadmadre", "fechadefuncion", "ips", "peso", "anoid"]
    column_renames:
      - original: "PersonaID"
        new: "personaid"
      - original: "Sexo"
        new: "sexo"
      - original: "RegimenAfiliacionSGSSS"
        new: "regimenafiliacion"
      - original: "Administradora"
        new: "administradora"
      - original: "CodigoPertenenciaEtnica"
        new: "codigoetnia"
      - original: "municipioResidencia"
        new: "municipioresidencia"
      - original: "SemanasGestacion"
        new: "semanasgestacion"
      - original: "EdadMadreMomentoDiagnostico"
        new: "edadmadre"
      - original: "FechaDefuncionAAAAMM"
        new: "fechadefuncion"
      - original: "IpsDondeRealizaParto"
        new: "ips"
      - original: "Peso"
        new: "peso"
      - original: "AnoID"
        new: "anoid"
    process: false
    error_file: "/home/agora/DataLake/ETL/errors/vitales/defunciones/defunciones_errados_test.txt"
    encoding: "latin1"
  - name: "sivigila"
    input_path: "hdfs:///rawdata/sivigila/"
    output_path: "hdfs:///stagedata/sivigila_test/"
    input_files: ["Sivigila_2008_2011.txt", "Sivigila_2012_2020.txt", "Sivigila_2021_2023.txt"]
    input_columns: ['PersonaBasicaID', 'Evento', 'AñoEpidemiologico', 'SemanaEpidemilogica', 'Prestador', 'CodigoAdministradora', 'Administradora', 'Edad', 'UnidadMedidaEdad', 'Sexo', 'TipoRegimen', 'codigoOcupacion', 'Ocupacion', 'Etnia', 'ClasificacioninicialCaso', 'PacienteHospitalizado', 'SeguimientoFinalCaso', 'FechaNotificacion', 'FechaConsulta', 'FechaInicioSINTOmas', 'FechaHospitalizacion', 'FechaDefuncion', 'FechaNcto', 'FechaAjuste', 'GP_Discapacidad', 'GP_Despazados', 'GP_Migrantes', 'GP_Carcelarios', 'GP_Gestantes', 'GP_Indigenas', 'GP_PoblacionICBF', 'GP_MadresComunitarias', 'GP_Desmovilizados', 'GP_Psiquia', 'GP_VictimasViolencia', 'GP_otros', 'codigoPaisOcurrencia', 'PaisOcurrencia', 'codigoDepartamentoOcurrencia', 'DepartamentoOcurrencia', 'codigoMunicipioOcurrencia', 'MunicipioOcurrencia', 'codigoDepartamentoNotificacion', 'DepartamentoNotificacion', 'codigoMunicipioNotificacion', 'MunicipioNotificacion', 'codigoDepartamentoResidencia', 'DepartamentoResidencia', 'codigoMunicipioResidencia', 'MunicipioResidencia', 'Area', 'CondicionFinal', 'CodigoDiagnosticoDefuncion', 'DiagnosticoDefuncion', 'TipoUPGD', 'EstadoFinalCaso', 'Confirmado']
    output_columns: ["personaid", "evento", "anioepidemiologico", "semanaepidemilogica", "prestador", "codigoadministradora", "administradora", "edad", "unidadmedidaedad", "sexo", "tiporegimen", "codigocupacion", "ocupacion", "etnia", "clasificacioninicialcaso", "pacientehospitalizado", "seguimientofinalcaso", "fechanotificacion", "fechaconsulta", "fechainiciosintomas", "fechahospitalizacion", "fechadefuncion", "fechancto", "fechaajuste", "gp_discapacidad", "gp_despazados", "gp_migrantes", "gp_carcelarios", "gp_gestantes", "gp_indigenas", "gp_poblacionicbf", "gp_madrescomunitarias", "gp_desmovilizados", "gp_psiquia", "gp_victimasviolencia", "gp_otros", "codigopaisocurrencia", "paisocurrencia", "codigodepartamentoocurrencia", "departamentoocurrencia", "codigomunicipioocurrencia", "municipioocurrencia", "codigodepartamentonotificacion", "departamentonotificacion", "codigomunicipionotificacion", "municipionotificacion", "codigodepartamentoresidencia", "departamentoresidencia", "codigomunicipioresidencia", "municipioresidencia", "area", "condicionfinal", "codigodiagnosticodefuncion", "diagnosticodefuncion", "tipoupgd", "estadofinalcaso", "confirmado"]
    column_renames:
      - original: "PersonaBasicaID"
        new: "personaid"
      - original: "Evento"
        new: "evento"
      - original: "AñoEpidemiologico"
        new: "anioepidemiologico"
      - original: "SemanaEpidemilogica"
        new: "semanaepidemilogica"
      - original: "Prestador"
        new: "prestador"
      - original: "CodigoAdministradora"
        new: "codigoadministradora"
      - original: "Administradora"
        new: "administradora"
      - original: "Edad"
        new: "edad"
      - original: "UnidadMedidaEdad"
        new: "unidadmedidaedad"
      - original: "Sexo"
        new: "sexo"
      - original: "TipoRegimen"
        new: "tiporegimen"
      - original: "codigoOcupacion"
        new: "codigocupacion"
      - original: "Ocupacion"
        new: "ocupacion"
      - original: "Etnia"
        new: "etnia"
      - original: "ClasificacioninicialCaso"
        new: "clasificacioninicialcaso"
      - original: "PacienteHospitalizado"
        new: "pacientehospitalizado"
      - original: "SeguimientoFinalCaso"
        new: "seguimientofinalcaso"
      - original: "FechaNotificacion"
        new: "fechanotificacion"
      - original: "FechaConsulta"
        new: "fechaconsulta"
      - original: "FechaInicioSINTOmas"
        new: "fechainiciosintomas"
      - original: "FechaHospitalizacion"
        new: "fechahospitalizacion"
      - original: "FechaDefuncion"
        new: "fechadefuncion"
      - original: "FechaNcto"
        new: "fechancto"
      - original: "FechaAjuste"
        new: "fechaajuste"
      - original: "GP_Discapacidad"
        new: "gp_discapacidad"
      - original: "GP_Despazados"
        new: "gp_despazados"
      - original: "GP_Migrantes"
        new: "gp_migrantes"
      - original: "GP_Carcelarios"
        new: "gp_carcelarios"
      - original: "GP_Gestantes"
        new: "gp_gestantes"
      - original: "GP_Indigenas"
        new: "gp_indigenas"
      - original: "GP_PoblacionICBF"
        new: "gp_poblacionicbf"
      - original: "GP_MadresComunitarias"
        new: "gp_madrescomunitarias"
      - original: "GP_Desmovilizados"
        new: "gp_desmovilizados"
      - original: "GP_Psiquia"
        new: "gp_psiquia"
      - original: "GP_VictimasViolencia"
        new: "gp_victimasviolencia"
      - original: "GP_otros"
        new: "gp_otros"
      - original: "codigoPaisOcurrencia"
        new: "codigopaisocurrencia"
      - original: "PaisOcurrencia"
        new: "paisociurrencia"
      - original: "codigoDepartamentoOcurrencia"
        new: "codigodepartamentoocurrencia"
      - original: "DepartamentoOcurrencia"
        new: "departamentoocurrencia"
      - original: "codigoMunicipioOcurrencia"
        new: "codigomunicipioocurrencia"
      - original: "MunicipioOcurrencia"
        new: "municipioocurrencia"
      - original: "codigoDepartamentoNotificacion"
        new: "codigodepartamentonotificacion"
      - original: "DepartamentoNotificacion"
        new: "departamentonotificacion"
      - original: "codigoMunicipioNotificacion"
        new: "codigomunicipionotificacion"
      - original: "MunicipioNotificacion"
        new: "municipionotificacion"
      - original: "codigoDepartamentoResidencia"
        new: "codigodepartamentoresidencia"
      - original: "DepartamentoResidencia"
        new: "departamentoresidencia"
      - original: "codigoMunicipioResidencia"
        new: "codigomunicipioresidencia"
      - original: "MunicipioResidencia"
        new: "municipioresidencia"
      - original: "Area"
        new: "area"
      - original: "CondicionFinal"
        new: "condicionfinal"
      - original: "CodigoDiagnosticoDefuncion"
        new: "codigodiagnosticodefuncion"
      - original: "DiagnosticoDefuncion"
        new: "diagnosticodefuncion"
      - original: "TipoUPGD"
        new: "tipoupgd"
      - original: "EstadoFinalCaso"
        new: "estadofinalcaso"
      - original: "Confirmado"
        new: "confirmado"
    process: false
    error_file: "/home/agora/DataLake/ETL/errors/sivigila/sivigila_errados_test.txt"
    encoding: "latin1"

# Configuración de la salida
output:
  max_file_size_mb: 32

# Configuración de Spark
spark:
  log_gc_path: "/home/agora/DataLake/ETL/logs/driver-gc.log"
